export const esseFiresProductsMetaData = [
  {
    brand: "Esse Fires",
    name: "700 wood heater",
    slug: "700-wood-heater",
    title: "Esse 700 Wood Heater - Living Fire",
    description: "",
    type: "product",
    keywords: "Esse, 700, wood heater, wood burning, Living Fire",
  },
  {
    brand: "Esse Fires",
    name: "700 Wood Heater - Outside Air",
    slug: "700-wood-heater-outside-air",
    title: "Esse 700 Wood Heater - Outside Air - Living Fire",
    description: "",
    type: "product",
    keywords: "Esse, 700, wood heater, outside air, wood burning, Living Fire",
  },
  {
    brand: "Esse Fires",
    name: "775 Wood Heater - Outside Air",
    slug: "775-wood-heater-outside-air",
    title: "Esse 775 Wood Heater - Outside Air - Living Fire",
    description: "",
    type: "product",
    keywords: "Esse, 775, wood heater, outside air, wood burning, Living Fire",
  },
  {
    brand: "Esse Fires",
    name: "Vector",
    slug: "vector",
    title: "Esse Vector - Living Fire",
    description: "",
    type: "product",
    keywords: "Esse, Vector, wood stove, Living Fire",
  },
  {
    brand: "Esse Fires",
    name: "Ironheart - Outside Air - Dry",
    slug: "ironheart-outside-air-dry",
    title: "Esse Ironheart - Outside Air - Dry - Living Fire",
    description: "",
    type: "product",
    keywords: "Esse, Ironheart, outside air, dry, wood stove, Living Fire",
  },
  {
    brand: "Esse Fires",
    name: "Ironheart - Outside Air - Wet",
    slug: "ironheart-outside-air-wet",
    title: "Esse Ironheart - Outside Air - Wet - Living Fire",
    description: "",
    type: "product",
    keywords: "Esse, Ironheart, outside air, wet, wood stove, Living Fire",
  },
  {
    brand: "Esse Fires",
    name: "Ironheart Dry",
    slug: "ironheart-dry",
    title: "Esse Ironheart Dry - Living Fire",
    description: "",
    type: "product",
    keywords: "Esse, Ironheart, dry, wood stove, Living Fire",
  },
  {
    brand: "Esse Fires",
    name: "Ironheart Wet",
    slug: "ironheart-wet",
    title: "Esse Ironheart Wet - Living Fire",
    description: "",
    type: "product",
    keywords: "Esse, Ironheart, wet, wood stove, Living Fire",
  },
  {
    brand: "Esse Fires",
    name: "Bakeheart - Outside Air - Dry",
    slug: "bakeheart-outside-air-dry",
    title: "Esse Bakeheart - Outside Air - Dry - Living Fire",
    description: "",
    type: "product",
    keywords: "Esse, Bakeheart, outside air, dry, wood stove, Living Fire",
  },
  {
    brand: "Esse Fires",
    name: "Bakeheart - Outside Air - Wet",
    slug: "bakeheart-outside-air-wet",
    title: "Esse Bakeheart - Outside Air - Wet - Living Fire",
    description: "",
    type: "product",
    keywords: "Esse, Bakeheart, outside air, wet, wood stove, Living Fire",
  },
  {
    brand: "Esse Fires",
    name: "Warmheart S - Outside Air - Dry",
    slug: "warmheart-s-outside-air-dry",
    title: "Esse Warmheart S - Outside Air - Dry - Living Fire",
    description: "",
    type: "product",
    keywords: "Esse, Warmheart S, outside air, dry, wood stove, Living Fire",
  },
  {
    brand: "Esse Fires",
    name: "Warmheart S - Outside Air - Wet",
    slug: "warmheart-s-outside-air-wet",
    title: "Esse Warmheart S - Outside Air - Wet - Living Fire",
    description: "",
    type: "product",
    keywords: "Esse, Warmheart S, outside air, wet, wood stove, Living Fire",
  },
  {
    brand: "Esse Fires",
    name: "1000 H",
    slug: "1000-h",
    title: "Esse 1000 H - Living Fire",
    description: "",
    type: "product",
    keywords: "Esse, 1000 H, wood stove, Living Fire",
  },
  {
    brand: "Esse Fires",
    name: "1000 W",
    slug: "1000-w",
    title: "Esse 1000 W - Living Fire",
    description: "",
    type: "product",
    keywords: "Esse, 1000 W, wood stove, Living Fire",
  },
];
