export const heatmasterProductsMetaData = [
  {
    brand: "Heatmaster",
    name: "Enviro - LPG Unit to Suit Coals",
    slug: "enviro-lpg-unit-to-suit-coals",
    title: "Enviro Inbuilt Gas Log Fire - Living Fire",
    description:
      "Discover our Enviro Inbuilt Fire here at Living Fire. Create a warm, cosy space perfect for larger-sized rooms. Get in touch to find out more!",
    type: "product",
    keywords:
      "Heatmaster, Enviro, LPG, gas log fire, inbuilt fireplace, coals, Living Fire, cosy heating",
  },
  {
    brand: "Heatmaster",
    name: "Seamless - Body",
    slug: "seamless-body",
    title: "Seamless Gas Log Fire - Living Fire",
    description:
      "Discover our Seamless Log Fire. Efficient, stylish design perfect for heating your home. Get in touch to find out more about our products!",
    type: "product",
    keywords:
      "Heatmaster, Seamless, gas log fire, efficient heating, stylish design, Living Fire",
  },
  {
    brand: "Heatmaster",
    name: "A-Series (A650 A750 A900)",
    slug: "a-series",
    title: "Heatmaster A-Series - Living Fire",
    description: "",
    type: "product",
    keywords:
      "Heatmaster, A-Series, A650, A750, A900, outdoor heater, Living Fire",
  },
  {
    brand: "Heatmaster",
    name: "A650 - Body",
    slug: "a650-body",
    title: "Heatmaster A650 - Living Fire",
    description: "",
    type: "product",
    keywords: "Heatmaster, A650, body, outdoor heater, Living Fire",
  },
  {
    brand: "Heatmaster",
    name: "A750 - Body",
    slug: "a750-body",
    title: "Heatmaster A750 - Living Fire",
    description: "",
    type: "product",
    keywords: "Heatmaster, A750, body, outdoor heater, Living Fire",
  },
  {
    brand: "Heatmaster",
    name: "A900 - Body",
    slug: "a900-body",
    title: "Heatmaster A900 - Living Fire",
    description: "",
    type: "product",
    keywords: "Heatmaster, A900, body, outdoor heater, Living Fire",
  },
  {
    brand: "Heatmaster",
    name: "B-Series",
    slug: "b-series",
    title: "Heatmaster B-Series - Living Fire",
    description: "",
    type: "product",
    keywords:
      "Heatmaster, B-Series, B650, B750, B900, outdoor heater, Living Fire",
  },
  {
    brand: "Heatmaster",
    name: "B650 - Body",
    slug: "b650-body",
    title: "Heatmaster B650 - Living Fire",
    description: "",
    type: "product",
    keywords: "Heatmaster, B650, body, outdoor heater, Living Fire",
  },
  {
    brand: "Heatmaster",
    name: "B750 - Body",
    slug: "b750-body",
    title: "Heatmaster B750 - Living Fire",
    description: "",
    type: "product",
    keywords: "Heatmaster, B750, body, outdoor heater, Living Fire",
  },
  {
    brand: "Heatmaster",
    name: "B900 - Body",
    slug: "b900-body",
    title: "Heatmaster B900 - Living Fire",
    description: "",
    type: "product",
    keywords: "Heatmaster, B900, body, outdoor heater, Living Fire",
  },
  {
    brand: "Heatmaster",
    name: "Z1200 - Unit",
    slug: "z1200-unit",
    title: "Heatmaster Z1200 - Unit - Living Fire",
    description: "",
    type: "product",
    keywords: "Heatmaster, Z1200, unit, outdoor heater, Living Fire",
  },
];
