export const kaloraProductsMetaData = [
  {
    brand: "kalora",
    name: "425R",
    slug: "425r",
    title: "KA425R Radiant - Wood Fireplace Range - Living Fire",
    description:
      "View Our Luxury Wood Fireplace Range Online Now Including The KA425R Radiant. For All Enquiries About Our Fireplace Products Contact Us Now!",
    type: "product",
    keywords:
      "kalora, 425R, KA425R, radiant fireplace, wood fireplace, luxury fireplace, Living Fire",
  },
  {
    brand: "kalora",
    name: "Fusion",
    slug: "fusion",
    title: "KAF50 Fusion - Wood Fireplace Range - Living Fire",
    description:
      "View Our Luxury Wood Fireplace Range Online Now Including The KAF50 Fusion. For All Enquiries About Our Fireplace Products Contact Us Now!",
    type: "product",
    keywords:
      "kalora, Fusion, KAF50, wood fireplace, luxury fireplace, Living Fire",
  },
  {
    brand: "kalora",
    name: "500C",
    slug: "500c",
    title: "KA500C Convection - Wood Fireplace Range - Living Fire",
    description:
      "View Our Luxury Wood Fireplace Range Online Now Including The KA500C Convection. For All Enquiries About Our Fireplace Products Contact Us Now!",
    type: "product",
    keywords:
      "kalora, 500C, KA500C, convection fireplace, wood fireplace, luxury fireplace, Living Fire",
  },
  {
    brand: "kalora",
    name: "600C",
    slug: "600c",
    title: "KA600C Convection - Wood Fireplace Range - Living Fire",
    description:
      "View Our Luxury Wood Fireplace Range Online Now Including The KA600C Convection. For All Enquiries About Our Fireplace Products Contact Us Now!",
    type: "product",
    keywords:
      "kalora, 600C, KA600C, convection fireplace, wood fireplace, luxury fireplace, Living Fire",
  },
  {
    brand: "kalora",
    name: "500BX Woodstack",
    slug: "500bx-woodstack",
    title: "KA500C Convection - Wood Fireplace Range - Living Fire",
    description:
      "View Our Luxury Wood Fireplace Range Online Now Including The KA500C Convection. For All Enquiries About Our Fireplace Products Contact Us Now!",
    type: "product",
    keywords:
      "kalora, 500BX, Woodstack, KA500C, convection fireplace, wood fireplace, luxury fireplace, Living Fire",
  },
  {
    brand: "kalora",
    name: "600BX Woodstack",
    slug: "600bx-woodstack",
    title: "KA600C Convection - Wood Fireplace Range - Living Fire",
    description:
      "View Our Luxury Wood Fireplace Range Online Now Including The KA600C Convection. For All Enquiries About Our Fireplace Products Contact Us Now!",
    type: "product",
    keywords:
      "kalora, 600BX, Woodstack, KA600C, convection fireplace, wood fireplace, luxury fireplace, Living Fire",
  },
  {
    brand: "kalora",
    name: "Sorrento",
    slug: "sorrento",
    title: "Sorrento Fireplace - Gas Range - Living Fire",
    description:
      "Shop our attractive gas, open-fire Sorrento fireplace range, guaranteed to impress any guests! For all enquiries about our products contact us now!",
    type: "product",
    keywords:
      "kalora, Sorrento, gas fireplace, open-fire, luxury fireplace, Living Fire",
  },
  {
    brand: "kalora",
    name: "Chalet 5",
    slug: "chalet-5",
    title: "Kalora Chalet 5 - Living Fire",
    description: "",
    type: "product",
    keywords: "kalora, Chalet 5, fireplace, Living Fire",
  },
  {
    brand: "kalora",
    name: "Chalet 6",
    slug: "chalet-6",
    title: "Kalora Chalet 6 - Living Fire",
    description: "",
    type: "product",
    keywords: "kalora, Chalet 6, fireplace, Living Fire",
  },
  {
    brand: "kalora",
    name: "Urban LS",
    slug: "urban-ls",
    title: "Kalora Urban LS - Living Fire",
    description: "",
    type: "product",
    keywords: "kalora, Urban LS, fireplace, Living Fire",
  },
  {
    brand: "kalora",
    name: "Urban PT",
    slug: "urban-pt",
    title: "Kalora Urban PT - Living Fire",
    description: "",
    type: "product",
    keywords: "kalora, Urban PT, fireplace, Living Fire",
  },
  {
    brand: "kalora",
    name: "Accent",
    slug: "accent",
    title: "Kalora Accent - Living Fire",
    description: "",
    type: "product",
    keywords: "kalora, Accent, fireplace, Living Fire",
  },
  {
    brand: "kalora",
    name: "Zenith Electric Fire - 36in",
    slug: "zenith-electric-fire-36in",
    title: "Kalora Zenith Electric Fire 36in - Living Fire",
    description: "",
    type: "product",
    keywords: "kalora, Zenith, electric fireplace, 36in, Living Fire",
  },
  {
    brand: "kalora",
    name: "Zenith Electric Fire - 42in",
    slug: "zenith-electric-fire-42in",
    title: "Kalora Zenith Electric Fire 42in - Living Fire",
    description: "",
    type: "product",
    keywords: "kalora, Zenith, electric fireplace, 42in, Living Fire",
  },
  {
    brand: "kalora",
    name: "Zenith Electric Fire - 60in",
    slug: "zenith-electric-fire-60in",
    title: "Kalora Zenith Electric Fire 60in - Living Fire",
    description: "",
    type: "product",
    keywords: "kalora, Zenith, electric fireplace, 60in, Living Fire",
  },
  {
    brand: "kalora",
    name: "Zenith Electric Fire - 72in",
    slug: "zenith-electric-fire-72in",
    title: "Kalora Zenith Electric Fire 72in - Living Fire",
    description: "",
    type: "product",
    keywords: "kalora, Zenith, electric fireplace, 72in, Living Fire",
  },
  {
    brand: "kalora",
    name: "Zenith Electric Fire - 88in",
    slug: "zenith-electric-fire-88in",
    title: "Kalora Zenith Electric Fire 88in - Living Fire",
    description: "",
    type: "product",
    keywords: "kalora, Zenith, electric fireplace, 88in, Living Fire",
  },
  {
    brand: "kalora",
    name: "Nexus Electric Fire - 36in",
    slug: "nexus-electric-fire-36in",
    title: "Kalora Nexus Electric Fire 36in - Living Fire",
    description: "",
    type: "product",
    keywords: "kalora, Nexus, electric fireplace, 36in, Living Fire",
  },
  {
    brand: "kalora",
    name: "Nexus Electric Fire - 50in",
    slug: "nexus-electric-fire-50in",
    title: "Kalora Nexus Electric Fire 50in - Living Fire",
    description: "",
    type: "product",
    keywords: "kalora, Nexus, electric fireplace, 50in, Living Fire",
  },
  {
    brand: "kalora",
    name: "Nexus Electric Fire - 60in",
    slug: "nexus-electric-fire-60in",
    title: "Kalora Nexus Electric Fire 60in - Living Fire",
    description: "",
    type: "product",
    keywords: "kalora, Nexus, electric fireplace, 60in, Living Fire",
  },
  {
    brand: "kalora",
    name: "Nexus Electric Fire - 74in",
    slug: "nexus-electric-fire-74in",
    title: "Kalora Nexus Electric Fire 74in - Living Fire",
    description: "",
    type: "product",
    keywords: "kalora, Nexus, electric fireplace, 74in, Living Fire",
  },
];
