import { NextResponse } from "next/server";
// export const runtime = 'edge'; 
  // Define URL alias mappings
  const urlAliases = {
  "/discount-fireplaces/albany-wood-heater": "/regency/albany",
  "/discount-fireplaces/alterra-wood-heater": "/regency/alterra",
  "/discount-fireplaces/berwick-wood-heater": "/regency/berwick",
  "/discount-fireplaces/bellerive-wood-heater": "/regency/bellerive",
  "/fireplace-brands/regency/wood-regency/cardinia-f150b-medium-radiant-heater": "/regency/cardinia",
  "/fireplace-brands/regency/gas-regency/regency-city-series-san-francisco-bay-40-gas-fireplace": "/regency/chicago-corner-40-left",
  "/fireplace-brands/regency/gas-regency/regency-city-series-san-francisco-bay-40-gas-fireplace": "/regency/chicago-corner-40-right",
  "/fireplace-brands/regency/electric/ei25-electric-insert": "/regency/ei25-electric-insert",
  "/gazco/estudio": "/gazco/estudio-es105r",
  "/gazco/estudio": "/gazco/estudio-es135r",
  "/gazco/estudio": "/gazco/estudio-es165r",
  "/gazco/estudio": "/gazco/estudio-es60r",
  "/gazco/estudio": "/gazco/estudio-es85r",
  "/discount-fireplaces/fg39-freestanding-gas-log-fire": "/regency/fg39",
  "/fireplace-range/gas-fireplaces/inbuilt-gas-fireplaces/gf1500-gas-log-fire": "/regency/gf1500l",
  "/fireplace-brands/regency/gas-regency/gf1500lst-double-sided-gas-log-fire": "/regency/gf1500lst-lpg",
  "/fireplace-range/gas-fireplaces/inbuilt-gas-fireplaces/gf950-gas-log-fire": "/regency/gf950l",
  "/fireplace-brands/regency/gfi750": "/regency/gfi750",
  "/discount-fireplaces/gosford-wood-heater": "/regency/gosford",
  "/fireplace-brands/regency/wood-regency/hume-wood-heater": "/regency/hume",
  "/discount-fireplaces/hz042-outdoor-gas-fireplace": "/regency/hzo42-outdoor",
  "/discount-fireplaces/hz042-outdoor-gas-fireplace": "/regency/hzo42-outdoor-lpg",
  "/discount-fireplaces/mansfield-double-sided-fireplace": "/regency/mansfield",
  "/fireplace-brands/regency/montrose-wood-heater": "/regency/montrose",
  "/discount-fireplaces/narrabri-wood-heater": "/regency/narrabri",
  "/fireplace-brands/regency/gas-regency/regency-city-series-san-francisco-bay-40-gas-fireplace": "/regency/new-york-view-40",
  "/fireplace-brands/regency/gas-regency/regency-city-series-san-francisco-bay-40-gas-fireplace": "/regency/new-york-view-60",
  "/fireplace-range/electric-fireplaces/landscape/onyx-110rw-modern-fireplace": "/gazco/onyx-110rw",
  "/gazco/onyx-modern-electric-fireplace": "/gazco/onyx-150rw",
  "/fireplace-range/electric-fireplaces/landscape/onyx-190rw": "/gazco/onyx-190rw",
  "/fireplace-range/gas-fireplaces/inbuilt-gas-fireplaces/pg36-gas-log-fire": "/regency/pg36",
  "/discount-fireplaces/renmark-wood-heater": "/regency/renmark",
  "/fireplace-brands/stovax/electric-stovax/riva2-670": "/gazco/riva2",
  "/fireplace-brands/regency/gas-regency/regency-city-series-san-francisco-bay-40-gas-fireplace": "/regency/san-francisco-bay-60",
  "/fireplace-brands/regency/gas-regency/regency-city-series-san-francisco-bay-40-gas-fireplace": "/regency/san-san-francisco-bay-40",
  "/fireplace-brands/stovax/wood-stovax/studio-2-freestanding": "/stovax/studio-2-freestanding",
  "/fireplace-range/wood-fireplaces/inbuilt-wood-fireplaces/studio-2-insert": "/stovax/studio-2-insert",
  "/fireplace-brands/regency/wood-regency/windsor-wood-heater-freestanding": "/regency/windsor",
  "/fireplace-brands/hergom/wood-hergom/glance-freestanding-fireplace": "/hergom/glance",
"/fireplace-brands/hergom/wood-hergom/glance-l-freestanding-fireplace": "/hergom/glance-l-freestanding",
"/fireplace-brands/hergom/wood-hergom/e-30m-freestanding-fireplace": "/hergom/e-30-freestanding",
"/fireplace-brands/hergom/wood-hergom/e-40-freestanding-fireplace": "/hergom/e-40-freestanding",
"/fireplace-brands/morso/wood-morso/6143-freestanding-fireplace": "/morso/6143-freestanding",
"/fireplace-brands/morso/wood-morso/6148-pedestal-fireplace": "/morso/6148-freestanding",
"/fireplace-brands/morso/wood-morso/7943-freestanding-fireplace": "/morso/7943-freestanding",
"/fireplace-brands/morso/wood-morso/7948-freestanding-fireplace": "/morso/7948-freestanding",
"/fireplace-brands/morso/wood-morso/7970-wood-burning-wall-mounted-fireplace": "/morso/7970-wall-mounted",
"/fireplace-brands/morso/wood-morso/8843-freestanding-fireplace": "/morso/8843-freestanding",
"/fireplace-brands/morso/wood-morso/classic-1410": "/morso/1410-freestanding",
"/fireplace-brands/morso/wood-morso/classic-1440": "/morso/1440-freestanding",
"/fireplace-range/wood-fireplaces/inbuilt-wood-fireplaces/linea-85-insert": "/adf/linea-85-insert",
"/fireplace-range/wood-fireplaces/inbuilt-wood-fireplaces/linea-100-insert": "/adf/linea-100-insert",
"/fireplace-brands/adf/wood-adf/linea-100-duo-insert": "/adf/linea-100-insert-duo",
"/fireplace-brands/adf/wood-adf/hayra-85-l-freestanding": "/adf/hayra-85vl-freestanding",
"/fireplace-brands/adf/wood-adf/hayra-85-vp-freestanding": "/adf/hayra-85vp-freestanding",
"/fireplace-brands/adf/wood-adf/linea-85-b-freestanding": "/adf/linea-85-b-freestanding",
"/fireplace-brands/adf/wood-adf/linea-100-b-freestanding": "/adf/linea-100-b-freestanding",
"/fireplace-brands/adf/wood-adf/linea-100-b-freestanding-copy": "/adf/linea-100-l-freestanding-with-steel-base",
"/fireplace-brands/adf/wood-adf/linea-100-b-freestanding-copy": "/adf/linea-100-duo-freestanding",
"/fireplace-brands/adf/wood-adf/linea-100-b-duo-freestanding": "/adf/linea-100-b-duo-l-freestanding-heater",
"/fireplace-brands/austroflamm/wood-austroflamm/clou-xtra-freestanding-fireplace": "/austroflamm/clou-xtra",
"/fireplace-brands/austroflamm/wood-austroflamm/dexter-freestanding-fireplace": "/austroflamm/dexter-door-hinge-left",
"/fireplace-brands/austroflamm/wood-austroflamm/dexter-freestanding-fireplace": "/austroflamm/dexter-door-hinge-right",
"/fireplace-range/wood-fireplaces/inbuilt-wood-fireplaces/120-45s-insert-fireplace": "/austroflamm/s120-45s-cassette",
"/fireplace-brands/kalora/ka425r-radiant": "/kalora/425r",
"/fireplace-brands/kalora/wood-kalora/kaf50-fusion": "/kalora/fusion",
"/fireplace-brands/kalora/wood-kalora/ka500c-convection": "/kalora/500c",
"/fireplace-brands/kalora/wood-kalora/ka600c-convection": "/kalora/600c",
"/fireplace-brands/kalora/wood-kalora/ka500c-convection": "/kalora/500bx-woodstack",
"/fireplace-brands/kalora/wood-kalora/ka600c-convection": "/kalora/600bx-woodstack",
"/fireplace-range/gas-fireplaces/inbuilt-gas-fireplaces/sorrento": "/kalora/sorrento",
"/fireplace-brands/eurostove/loxton-5-standard": "/eurostove/loxton-5-standard",
"/fireplace-brands/eurostove/churchill-5-dual-control": "/eurostove/churchill-5-dual-control",
"/fireplace-brands/eurostove/churchill-5-convection-dual-control": "/eurostove/churchill-5-convection-dual-control",
"/fireplace-brands/eurostove/churchill-5-convection-dual-control-logstore": "/eurostove/churchill-5-convection-dual-control-logstore",
"/fireplace-brands/paul-agnew-designs/ilektro-electric/ilektro-1250-landscape-tunnel": "/paul-agnew-designs/ilektro-1250-landscape-tunnel",
"/fireplace-brands/paul-agnew-designs/ilektro-electric/ilektro-twelve-fifty-landscape": "/paul-agnew-designs/ilektro-1250-landscape",
"/fireplace-brands/paul-agnew-designs/ilektro-electric/ilektro-sixteen-fifty-landscape": "/paul-agnew-designs/ilektro-1650-landscape",
"/fireplace-brands/paul-agnew-designs/ilektro-electric/ilektro-two-thousand-landscape": "/paul-agnew-designs/ilektro-2000-landscape",
"/fireplace-brands/paul-agnew-designs/ilektro-electric/ilektro-nine-fifty-aspect": "/paul-agnew-designs/ilektro-950-aspect",
"/fireplace-range/electric-fireplaces/landscape/ilektro-950-landscape": "/paul-agnew-designs/ilektro-950-landscape",
"/fireplace-brands/paul-agnew-designs/ilektro-950lt-electric-fireplace-transform-home": "/paul-agnew-designs/ilektro-950lt",
"/fireplace-brands/paul-agnew-designs/ilektro-freestanding-stove": "/paul-agnew-designs/ilektro-freestanding",
"/fireplace-brands/paul-agnew-designs/ilektro-woodland": "/paul-agnew-designs/ilektro-woodland-stove",
"/fireplace-brands/paul-agnew-designs/ilektro-electric/ilektro-slimline-50-120cm": "/paul-agnew-designs/ilektro-slimline-50in-1270mm",
"/fireplace-brands/paul-agnew-designs/ilektro-electric/ilektro-slimline-60-150cm": "/paul-agnew-designs/ilektro-slimline-60in-1524mm",
"/fireplace-brands/paul-agnew-designs/ilektro-electric/ilektro-slimline-72-180cm": "/paul-agnew-designs/ilektro-slimline-72in-1828mm",
"/fireplace-range/gas-fireplaces/inbuilt-gas-fireplaces/alto": "/paul-agnew-designs/alto-glass-fronted",
"/aerion-gas/alto-tunnel": "/paul-agnew-designs/alto-tunnel",
"/fireplace-range/gas-fireplaces/inbuilt-gas-fireplaces/quadro-eight-hundred": "/paul-agnew-designs/quadro-800-glass-fronted",
"/aerion-gas/quadro-tunnel": "/paul-agnew-designs/quadro-800-tunnel",
"/aerion-gas/vue-twelve-fifty-bay": "/paul-agnew-designs/vue-1250-bay",
"/fireplace-range/gas-fireplaces/inbuilt-gas-fireplaces/vue-twelve-fifty": "/paul-agnew-designs/vue-1250-glass-fronted",
"/fireplace-brands/paul-agnew-designs/vue-1250-left-corner-gas-fireplace": "/paul-agnew-designs/vue-1250-left-corner",
"/fireplace-brands/paul-agnew-designs/vue-1250-right-corner-gas-fireplace": "/paul-agnew-designs/vue-1250-right-corner",
"/aerion-gas/vue-bay": "/paul-agnew-designs/vue-1410-bay",
"/aerion-gas/vue-fourteen-ten-right-corner": "/paul-agnew-designs/vue-1410-glass-fronted",
"/fireplace-brands/paul-agnew-designs/vue-1410-left-corner-glass-gas-fireplace": "/paul-agnew-designs/vue-1410-left-corner",
"/fireplace-brands/paul-agnew-designs/vue-1410-right-corner-glass-gas-fireplace": "/paul-agnew-designs/vue-1410-right-corner",
"/aerion-gas/vue-peninsula": "/paul-agnew-designs/vue-1410-peninsula",
"/aerion-gas/vue-tunnel": "/paul-agnew-designs/vue-1410-tunnel",
"/fireplace-brands/paul-agnew-designs/hestia/1200-guillotine-tunnel": "/paul-agnew-designs/hestia-1200-guillotine-tunnel",
"/fireplace-brands/paul-agnew-designs/hestia/1400-guillotine-tunnel": "/paul-agnew-designs/hestia-1400-guillotine-tunnel",
"/fireplace-brands/paul-agnew-designs/hestia/1000-bay-guillotine": "/paul-agnew-designs/hestia-1000-bay-guillotine",
"/fireplace-brands/paul-agnew-designs/hestia/1000-guillotine-glass-fronted": "/paul-agnew-designs/hestia-1000-gf",
"/fireplace-brands/paul-agnew-designs/hestia/1400-guillotine-glass-fronted": "/paul-agnew-designs/hestia-1400-guillotine-glass-fronted",
"/fireplace-brands/paul-agnew-designs/hestia/1200-guillotine-glass-fronted": "/paul-agnew-designs/hestia-1200-guillotine-glass-fronted",
"/fireplace-brands/paul-agnew-designs/hestia/1000-peninsula-guillotine": "/paul-agnew-designs/hestia-1000-peninsula-guillotine",
"/fireplace-brands/paul-agnew-designs/i700": "/paul-agnew-designs/i700-stove",
"/fireplace-brands/paul-agnew-designs/modica-six-hundred-free-standing": "/paul-agnew-designs/modica-600-freestanding",
"/fireplace-brands/paul-agnew-designs/modern-wood-fireplaces-victoria": "/paul-agnew-designs/siena-750gf-freestanding",
"/fireplace-brands/paul-agnew-designs/siena-seven-fifty-right-sided-glass": "/paul-agnew-designs/siena-750gf2r",
"/fireplace-brands/paul-agnew-designs/siena-seven-fifty-left-sided-glass": "/paul-agnew-designs/siena-750gf2l",
"/fireplace-brands/paul-agnew-designs/siena-seven-fifty-three-sided-glass": "/paul-agnew-designs/siena-750gf3",
"/fireplace-brands/paul-agnew-designs/siena-seven-fifty-tunnel-freestanding": "/paul-agnew-designs/siena-750-tunnel-freestanding",
"/fireplace-brands/paul-agnew-designs/siena-seven-fifty-four-sided-glass-freestanding": "/paul-agnew-designs/siena-750-g4-freestanding",
"/cast-iron/mbf9": "/paul-agnew-designs/550-classic-fascia-black",
"/cast-iron/mbf11": "/paul-agnew-designs/700-classic-fascia-black",
"/cast-iron/700vb": "/paul-agnew-designs/700-decorative-fascia-black",
"/cast-iron/mbf1": "/paul-agnew-designs/700-victorian-fascia-polished",
"/cast-iron/mbf3": "/paul-agnew-designs/850-victorian-arch-fascia-black",
"/fireplace-brands/paul-agnew-designs/athena": "/paul-agnew-designs/athena-black-granite-1500",
"/fireplace-brands/paul-agnew-designs/camden-black": "/paul-agnew-designs/camden-insert-black",
"/fireplace-brands/paul-agnew-designs/petra-mantel/chilton": "/paul-agnew-designs/chilton-white-1370",
"/cast-iron/dublin-polished": "/paul-agnew-designs/dublin-insert-black",
"/fireplace-brands/paul-agnew-designs/petra-mantel/hampshire-2": "/paul-agnew-designs/hampshire-large-raw-1650",
"/etho-bio-ethanol/hampshire": "/paul-agnew-designs/hampshire-standard-raw-1500",
"/fireplace-brands/paul-agnew-designs/milos": "/paul-agnew-designs/milos-lu-grey-1310",
"/fireplace-brands/paul-agnew-designs/paros": "/paul-agnew-designs/paros-lu-grey-1459",
"/fireplace-brands/paul-agnew-designs/petra-mantel/riversdale": "/paul-agnew-designs/riversdale-white-1500",
"/fireplace-brands/paul-agnew-designs/petra-mantel/victorian-arched-mantle-white-carrara": "/paul-agnew-designs/victorian-arched-italian-cararra-1650",
"/fireplace-brands/paul-agnew-designs/petra-mantel/victorian-square-mocha-beige": "/paul-agnew-designs/victorian-corbel-mocha-beige-1470",
"/fireplace-brands/paul-agnew-designs/vic-corbel-limestone": "/paul-agnew-designs/victorian-corbel-mocha-beige-1500",
"/fireplace-brands/paul-agnew-designs/petra-mantel/victorian-corbel": "/paul-agnew-designs/victorian-corbel-white-1470",
"/fireplace-range/fireplace-mantels/marble-italian-carrara/windsor-white-carrara/": "/paul-agnew-designs/windsor-italian-cararra-1650",
"/fireplace-range/gas-fireplaces/inbuilt-gas-fireplaces/enviro-inbuilt-gas-log-fire": "/heatmaster/enviro-lpg-unit-to-suit-coals",
"/fireplace-range/gas-fireplaces/inbuilt-gas-fireplaces/seamless-gas-log-fire": "/heatmaster/seamless-body",
 "/fireplace-range/wood-fireplaces": "/allProducts/wood",
  "/fireplace-range/wood-fireplaces/inbuilt-single-sided": "/allProducts/wood/inbuilt/single-sided",
  "/fireplace-range/wood-fireplaces/cast-iron-wood": "/allProducts/cast-iron/wood",
  "/fireplace-range/wood-fireplaces/freestanding": "/allProducts/wood/freestanding",
  "/fireplace-range/wood-fireplaces/double-sided": "/allProducts/wood/two-sided",
  "/fireplace-range/wood-fireplaces/three-sided": "/allProducts/wood/three-sided",
  "/fireplace-range/wood-fireplaces/inbuilt-chimney": "/allProducts/wood/inbuilt",
  "/fireplace-range/wood-fireplaces/outdoor": "/allProducts/wood/outdoor",
  "/fireplace-range/wood-fireplaces/inbuilt-wood-fireplaces": "/allProducts/wood/inbuilt",
  "/fireplace-range/gas-fireplaces": "/allProducts/gas",
  "/fireplace-range/gas-fireplaces/inbuilt-single-sided-gas": "/allProducts/gas/inbuilt/single-sided",
  "/fireplace-range/gas-fireplaces/double-sided-gas": "/allProducts/gas/inbuilt/two-sided",
  "/fireplace-range/gas-fireplaces/three-sided-gas": "/allProducts/gas/inbuilt/three-sided",
  "/fireplace-range/gas-fireplaces/freestanding-gas": "/allProducts/gas/freestanding",
  "/fireplace-range/gas-fireplaces/outdoor-gas": "/allProducts/gas/outdoor",
  "/fireplace-range/gas-fireplaces/chimney-inbuilt": "/allProducts/gas/inbuilt",
  "/fireplace-range/gas-fireplaces/inbuilt-gas-fireplaces": "/allProducts/gas/inbuilt",
  "/fireplace-range/electric-fireplaces": "/allProducts/electric",
  "/fireplace-range/electric-fireplaces/freestanding-suite-electric": "/allProducts/electric/freestanding",
  "/fireplace-brands/paul-agnew-designs": "/allProducts/paul-agnew-designs",
  "/fireplace-brands/paul-agnew-designs/pyro-wood": "/allProducts/paul-agnew-designs/pyro/wood",
  "/fireplace-brands/paul-agnew-designs/hestia": "/allProducts/paul-agnew-designs/hestia",
  "/fireplace-brands/eurostove": "/allProducts/eurostove",
  "/fireplace-brands/regency": "/allProducts/regency",
  "/fireplace-brands/regency/gas-regency": "/allProducts/regency/gas",
  "/fireplace-brands/regency/wood-regency": "/allProducts/regency/wood",
  "/fireplace-brands/stovax": "/allProducts/stovax",
  "/fireplace-brands/stovax/wood-stovax": "/allProducts/stovax/wood",
  "/fireplace-brands/stovax/electric-stovax": "/allProducts/stovax/electric",
  "/fireplace-brands/austroflamm": "/allProducts/austroflamm",
  "/fireplace-brands/austroflamm/wood-austroflamm": "/allProducts/austroflamm/wood",
  "/fireplace-brands/morso": "/allProducts/morso",
  "/fireplace-brands/morso/gas-morso": "/allProducts/morso/gas",
  "/fireplace-brands/morso/wood-morso": "/allProducts/morso/wood",
  "/fireplace-brands/heatmaster": "/allProducts/heatmaster",
  "/fireplace-brands/heatmaster/gas-heatmaster": "/allProducts/heatmaster/gas",
  "/fireplace-brands/heatmaster/wood-heatmaster": "/allProducts/heatmaster/wood",
  "/fireplace-brands/hergom": "/allProducts/hergom",
  "/fireplace-brands/hergom/wood-hergom": "/allProducts/hergom/wood",
  "/fireplace-brands/adf": "/allProducts/adf",
  "/fireplace-brands/adf/wood-adf": "/allProducts/adf/wood",
  "/fireplace-brands/kalora": "/allProducts/kalora",
  "/fireplace-brands/kalora/gas-kalora": "/allProducts/kalora/gas",
  "/fireplace-brands/kalora/wood-kalora": "/allProducts/kalora/wood",
  "/fireplace-range/bioethanol-fireplaces": "/allProducts/bio-ethanol",
  "/fireplace-range/bioethanol-fireplaces/inbuilt-suite": "/allProducts/bio-ethanol/inbuilt",
  "/fireplace-range/bioethanol-fireplaces/freestanding-suite": "/allProducts/bio-ethanol/freestanding",
  "/fireplace-range/fireplace-mantels": "/allProducts/fireplace-mantels",
  "/fireplace-range/cast-iron-fireplaces": "/allProducts/cast-iron",
  "/fireplace-range/fireplace-accessories": "/allProducts/fire-tools",
  "/our-story": "/our-story",
  "/contact-us": "/contact",
  "/warranty-servicing": "/maintenance-service"
};
export const config = {
  matcher: [
    '/((?!_next/static|_next/image|favicon.ico|api|_next/data).*)',
  ],
}
export function middleware(req) {
  const response = NextResponse.next();
  console.log("middleware")
  // Log to check if middleware is being executed

  // Set CORS headers
  response.headers.set("Access-Control-Allow-Origin", "*");
  response.headers.set("Access-Control-Allow-Methods", "GET, POST, OPTIONS");
  response.headers.set(
    "Access-Control-Allow-Headers",
    "Content-Type, Authorization"
  );

  // Handle preflight requests
  if (req.method === "OPTIONS") {
   return new Response(null, { status: 204, headers: response.headers });
  }



  const url = req.nextUrl.clone();
  // Check if the requested path matches an alias
  if (urlAliases[url.pathname]) {
    url.pathname = urlAliases[url.pathname];
    // return NextResponse.rewrite(url);  
    return NextResponse.redirect(url);
  }

  return response;
}
